config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index'
  get '/tasks/:id', to: 'tasks#show', as: :task
  get '/new', to: 'tasks#new', as: :new
  post '/tasks', to: 'tasks#create', as: :create
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch '/tasks/:id', to: 'tasks#update', as: :update
  delete '/tasks/:id', to: 'tasks#destroy', as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)

    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for task do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit label, class: 'btn btn-primary' %> or <%= link_to 'Cancel', tasks_path %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h2>Edit <%= @task %></h2>

<%= render 'form', task: @task, label: 'Edit task'  %>

<p> <%= link_to 'Back to List', tasks_path %></p>

app/views/tasks/index.html.erb
<h2>Task List</h2>

<ul>
  <% @tasks.each do |task| %>
  <li><%= task.completed ? '☑️' : '🔲' %> <%= link_to task.title, task %> <%= link_to '🗑', delete_path(task), method: :delete, data: { confirm: 'Are you sure you want to delete this task?'} %>
  </li>
  <% end %>
</ul>

<p> <%= link_to 'Add a New Task', new_path %></p>

app/views/tasks/new.html.erb
<h2>New Task</h2>

<%= render 'form', task: @task, label: 'Create task'  %>

<!-- <form action="/tasks" method="post">
   <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="title">Title</label>
  <input id="title" type="text" name="title">

  <label for="details">Details</label>
  <input id="details" type="text" name="details">

  <input type="submit">
</form> -->

<p> <%= link_to 'Back to List', tasks_path %></p>

app/views/tasks/show.html.erb
<h2> <%= @task.title %></h2>

<p> <%= @task.details %></p>

<p> <%= link_to 'Edit Task', edit_path %></p>
<p> <%= link_to '🗑', delete_path(@task), method: :delete, data: { confirm: 'Are you sure you want to delete this task?'} %></p>

<p> <%= link_to 'Back to List', tasks_path %></p>